### ISSUE TITLE
language and langid remain for values eng and en

### ISSUE THREAD

**Issue by chreliot** [twsh/Convertbibliography#3]
The script is removing `language` and `langid` fields with value `English,` but not those with values `eng` or `en`, which I'm seeing in a large .bib file generated by Zotero.

(I would personally be happy with those fields being removed entirely, but maybe they're of value to someone.)

**Comment by twsh** [comment]
Thanks. I should remove 'eng' and 'en' too.

They're useful if you do have things written in multiple languages and you want to  e.g. use sentence case with the entries in French and title case with those in English.

**Comment by twsh** [comment]
I think there might be a problem with the .bib file you have. If I understand what's in the Biblatex manual, and this answer https://tex.stackexchange.com/questions/294703/can-i-use-a-shortened-language-entry-language-code-in-my-bib-file , the `language` field should be a language name as it would be printed e.g. 'English', 'French'. The `langid` field can be an identifier from Table 2 of the manual e.g. 'british', 'french', or a code like 'en', 'fr'. My Zotero output populates `langid` but not `language` with the full identifier.

**Comment by twsh** [comment]
I have made some changes in https://github.com/twsh/Convertbibliography/commit/738c4d3426252a5034a9c6d10bae82c50e8b5730

The script removes `language` and `langid` when `language` is 'English', otherwise it copies `language` to `langid`. It warns if there is a `language` but no `langid`. This assumes that `language` is a descriptor, and that you don't want either field populated for 'English'. If they're not then biblatex will use the language set by Babel/Polyglossia.
